name: CI

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  rust-core-check:
    name: Build & Test core
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: core

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        run: cargo build --release

      - name: Run Tests
        run: cargo test --all
